languageCode = "zh-CN"
title = "K.I.S.S"
description = "Keep It Simple, Stupid"

baseURL = "https://bigeagle.me"
copyright = "&copy; <a href=\"https://github.com/bigeagle\"> Justin Wong</a> 2021"

disqusShortname = "bigeagle"
googleAnalytics = ""

disablePathToLower = true
hasCJKLanguage = true

buildFuture = true

[permalinks]
post = "/:year/:month/:slug/"

[taxcnomies]
tag = "tags"

[params.social]
twitter = "bigeagle_xd"
github = "bigeagle"
rss = "index.xml"
about = "about"

[params.social.config]
platforms = ["about", "rss", "github", "twitter"]


[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Justin Wong" # Author full name
authorEmail = "" # Author email

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "K.I.S.S" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = false # Add copy button above code blocks
taxonomiesCount = true # Add taxonomies count

[params.features]
disqusOnDemand = true  # Load Disqus comments on click
