languageCode = "zh-CN"
title = "K.I.S.S"
description = "Keep It Simple, Stupid"

baseURL = "https://bigeagle.me"
theme = 'hemingway2'
copyright = "&copy; <a href=\"https://github.com/bigeagle\"> Justin Wong</a> 2020"


disqusShortname = "bigeagle"
googleAnalytics = ""

disablePathToLower = true
hasCJKLanguage = true

[permalinks]
post = "/:year/:month/:slug/"

[taxcnomies]
tag = "tags"

[params]
baseURL = "https://bigeagle.me"

[params.highlight]
style = "github"

[[params.social]]
url = "/about"
fa_icon = "fa-user"
name = "About"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
name = "RSS"

[blackfriday]
  smartypants = false

[markup.goldmark.renderer]
unsafe= true
